"""Doctor-related database models"""
import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, Boolean, Float, DateTime, Integer, ForeignKey, JSON
from sqlalchemy.ext.declarative import declarative_base
from database.models import Base


class Doctor(Base):
    """Doctor profile table"""
    __tablename__ = "doctors"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String(36), unique=True, nullable=False)  # Link to auth user
    name = Column(String(200), nullable=False)
    email = Column(String(200), unique=True, nullable=False)
    phone = Column(String(50))
    specialization = Column(String(200))
    license_number = Column(String(100))
    bio = Column(Text)
    experience_years = Column(Integer, default=0)
    rating = Column(Float, default=0.0)
    total_reviews = Column(Integer, default=0)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Patient(Base):
    """Patient profile table"""
    __tablename__ = "patients"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String(36), unique=True, nullable=False)  # Link to auth user
    name = Column(String(200), nullable=False)
    email = Column(String(200), unique=True, nullable=False)
    phone = Column(String(50))
    date_of_birth = Column(DateTime)
    gender = Column(String(20))
    medical_history = Column(JSON)  # Store as JSON
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Appointment(Base):
    """Appointment table"""
    __tablename__ = "appointments"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    doctor_id = Column(String(36), ForeignKey('doctors.id'), nullable=False)
    patient_id = Column(String(36), ForeignKey('patients.id'), nullable=False)
    session_id = Column(String(100), index=True)  # Link to chat session
    scheduled_at = Column(DateTime, nullable=False)
    duration_minutes = Column(Integer, default=30)
    reason = Column(Text)
    notes = Column(Text)
    status = Column(String(50), default='pending')  # pending, confirmed, completed, cancelled
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Prescription(Base):
    """Prescription table"""
    __tablename__ = "prescriptions"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    doctor_id = Column(String(36), ForeignKey('doctors.id'), nullable=False)
    patient_id = Column(String(36), ForeignKey('patients.id'), nullable=False)
    appointment_id = Column(String(36), ForeignKey('appointments.id'))
    medicines = Column(JSON, nullable=False)  # List of medicines with dosage
    diagnosis = Column(Text)
    notes = Column(Text)
    status = Column(String(50), default='active')  # active, completed, cancelled
    issued_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    valid_until = Column(DateTime)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class DoctorRecommendation(Base):
    """Doctor recommendations generated by AI during chat"""
    __tablename__ = "doctor_recommendations"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String(100), index=True, nullable=False)
    patient_id = Column(String(36), ForeignKey('patients.id'))
    recommended_specialization = Column(String(200))
    reason = Column(Text, nullable=False)
    urgency = Column(String(50), default='normal')  # low, normal, high, urgent
    symptoms = Column(JSON)  # List of detected symptoms
    emotion_context = Column(JSON)  # Emotion analysis that triggered recommendation
    recommended_doctors = Column(JSON)  # List of doctor IDs
    is_crisis = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
