services:
  - type: web
    name: offline-health-assistant-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: APP_NAME
        value: Offline Health Assistant API
      - key: APP_ENV
        value: production
      - key: API_PREFIX
        value: /api/v1
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        value: mongodb://localhost:27017
      - key: MONGO_DB_NAME
        value: health_assistant
